[keys.normal]
n = "move_line_down"
N = "join_selections"
"A-N" = "join_selections_space"
e = "move_line_up"
E = "keep_selections"
"A-E" = "remove_selections"
i = "move_char_right"
I = "no_op"

j = "move_next_word_end"
J = "move_next_long_word_end"
k = "search_next"
K = "search_prev"
l = "insert_mode"
L = "insert_at_line_start"

C-n = "goto_line_start"
C-e = "goto_line_end"

[keys.insert]
C-o = "normal_mode"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
