"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"
email = "jacmoe.dk@gmail.com"

[ui]
pager = ":builtin"
default-command = "log"

[user]
name = "Jacob Moena"
email = "jacmoe.dk@gmail.com"
