[mgr]
      prepend_keymap = [
        # Hopping
	{ on = "e", run = "arrow prev", desc = "Previous file" },
	{ on = "n", run = "arrow next", desc = "Next file" },

        # Navigation
	{ on = "i", run = "enter", desc = "Enter the child directory" },

	{ on = "I", run = "forward", desc = "Forward to next directory" },

	# Seeking
	{ on = "E", run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = "N", run = "seek 5",  desc = "Seek down 5 units in the preview" },

        # Lazygit
        { on = ["g", "i"], run = "plugin lazygit", desc = "run lazygit" },
        # Bunny
        { on = ["g", "b"], run = "plugin bunny", desc = "run bunny" },
      ]

[tasks]
      prepend_keymap = [
      	{ on = "e", run = "arrow prev", desc = "Previous task" },
        { on = "n", run = "arrow next", desc = "Next task" },
      ]

[spot]
      prepend_keymap = [
      	{ on = "e", run = "arrow prev", desc = "Previous line" },
        { on = "n", run = "arrow next", desc = "Next line" },
        { on = "i", run = "swipe next", desc = "Swipe to next file" },
      ]

[pick]
      prepend_keymap = [
      	{ on = "e", run = "arrow prev", desc = "Previous option" },
        { on = "n", run = "arrow next", desc = "Next option" },
      ]

[input]
      prepend_keymap = [
      	# Mode
      	{ on = "u", run = "insert",                          desc = "Enter insert mode" },
      	{ on = "U", run = [ "move first-char", "insert" ],   desc = "Move to the BOL, and enter insert mode" },

        # Character-wise movement
      	{ on = "i", run = "move 1",  desc = "Move forward a character" },

        # Word-wise movement
        { on = "f",     run = "forward --end-of-word",       desc = "Move forward to the end of the current or next word" },
        { on = "F",     run = "forward --far --end-of-word", desc = "Move forward to the end of the current or next WORD" },
      ]

[confirm]
      prepend_keymap = [
      	{ on = "c", run = "close", desc = "Cancel the confirm" },
      	{ on = "e", run = "arrow prev", desc = "Previous line" },
        { on = "n", run = "arrow next", desc = "Next line" },
      ]

[cmp]
      prepend_keymap = [
      	{ on = "<A-e>", run = "arrow prev", desc = "Previous item" },
        { on = "<A-n>", run = "arrow next", desc = "Next item" },
      ]

[help]
      prepend_keymap = [
      	# Navigation
        { on = "e", run = "arrow prev", desc = "Previous line" },
        { on = "n", run = "arrow next", desc = "Next line" },
      ]

